### ISSUE TITLE
Attribute Nesting Not Working As described

### ISSUE THREAD

**Issue by rwilsond** [zaus/forms-3rdparty-xpost#11]
I am looking to submit the following:

```json
"Phone": [
                  {
                    "@attributes": {
                      "PhoneType": "personal"
                    },
                    "PhoneNumber": "999-999-9999"
                  },
                  {
                    "@attributes": {
                      "PhoneType": "cell"
                    },
                    "PhoneNumber": "777-777-7777"
                  },
                  {
                    "@attributes": {
                      "PhoneType": "office"
                    },
                    "PhoneNumber": "111-111-1111"
                  }
                ]
```

But when I actually do it I get:

```json
"Phone":{
                        "@attributes":"personal, cell, office",
                        "PhoneNumber":"999-999-9999, 777-777-7777, 111-111-1111"
                     },
```

(The above resulted when using the default ", " separator.)

I then tried the following as well (without the quotes): "[]", "[] ", "[#] ", and "[#]" and none worked. Sometimes it would just add [] as if it were the comma, most of the time it just returned nothing in the post body (not valid JSON.)

In my case, I really only need to submit a phone number for Personal, and I can leave cell and office blank, but in the example above I added phone numbers to make it easier to follow.

Either way works (with blank cell and office numbers, or filler cell and office numbers).

I feel like I am overlooking something obvious, but I'm having a tough time figuring this out. 

Any help would be appreciated IMMENSELY!

I'm running WP 4.1.1
Gravity Forms 1.9.6
Forms 3rd Party 1.6.4.1
Forms-3rdparty Xml Post 1.0

**Comment by zaus** [comment]
Sorry I didn't get to you sooner -- what mapping are you using?

**Comment by zaus** [comment]
Correction -- can you post the entire debug email (mapping + submission)

**Comment by zaus** [comment]
I tried guessing what could be coming across, not sure how you would set up a mapping to get what you want though -- http://sandbox.onlinephpfunctions.com/code/ca567488dae392bf881d297b6cc0bc7016e2bbd3

**Comment by zaus** [comment]
Interesting, numeric indices aren't supported very well...
http://sandbox.onlinephpfunctions.com/code/8cfdbcf5419a5b23cef6417ad20a7252546c34d3

	$result = nest(array(
		'Phone/a/@attributes/PhoneType' => 'personal',
		'Phone/a/PhoneNumber' => '999-999-9999',

		'Phone/b/@attributes/PhoneType' => 'work',
		'Phone/b/PhoneNumber' => '123-456-7899',

		'Phone/c/@attributes/PhoneType' => 'cell',
		'Phone/c/PhoneNumber' => '222-222-2222',
	));

**Comment by zaus** [comment]
Aha - http://sandbox.onlinephpfunctions.com/code/4e788f1c8a7c545870caf834cbc08108a76d4f5a

So [`array_merge_recursive`](http://php.net/manual/en/function.array-merge-recursive.php) (used [here](https://github.com/zaus/forms-3rdparty-xpost/blob/master/forms-3rdparty-xpost.php#L168)) copies numeric indexes rather than overwriting them.  A [custom recursive merge](http://php.net/manual/en/function.array-merge-recursive.php#82976) will support them, but then the problem becomes how would you set up a mapping so that multiple responses don't essentially put the index at the end of the key mapping, but rather somewhere inside...

**Comment by zaus** [comment]
And here's the trick -- need a new "separator style" `[%]` which will let us put the index as a placeholder in the mapped field, like:

````
$submission = array(
	'Phone/%i/@attributes/PhoneType' => array('personal', 'work', 'cell'),
	'Phone/%i/PhoneNumber' => array('999-999-9999', '123-456-7899',
'222-222-2222'),
);
````

````
function placeholder_separator($post) {
	$new = array(); // add results to new so we don't pollute the enumerator
	// find the arrays and reformat keys with index
	foreach($post as $f => $v) {
		if(is_array($v)) {
			// for each item in the submission array,
			// get its numerical index and replace the
			// placeholder in the destination field
			
			foreach($v as $i => $p) {
				$k = str_replace('%i', $i, $f);
				$new[$k] = $p;
			}
			
			unset($post[$f]); // now remove original, since we need to reattach under a different key
		}
	}
	return array_merge($post, $new);
}
````

see http://sandbox.onlinephpfunctions.com/code/5c2a626f6e5590281412863c7c3b14b143d935a7

**Comment by rwilsond** [comment]
Hey, sorry I wasn't online last night to respond.

So you're saying if I add the function placeholder_separator to my website it should work?

(I am assuming I would add it to my functions.php in Wordpress?)

**Comment by zaus** [comment]
Sorry for the late response -- you'd actually need to modify the plugin and add the case statement [here](https://github.com/zaus/forms-3rdparty-integration/blob/master/forms-3rdparty-integration.php#L466) to call the function I wrote above.  It'd be a good addition, as I linked the enhancement issue (pull request anyone?)

**Comment by rwilsond** [comment]
Hi Zaus,

No worries!

Do you have an example showing how you added the case statement? I am having trouble applying your solution.

Thanks in advance, I'd be very grateful.

**Comment by zaus** [comment]
Assuming resolved due to 'native support' for this feature per referenced commit.
