### ISSUE TITLE
root xml element <post> can't be ignored

### ISSUE THREAD

**Issue by bastijan** [zaus/forms-3rdparty-xpost#14]
I dont need root elements

But if i leave Root element(s) empty I got XML with "post" root element.

How to exclude root element in settings?

**Comment by zaus** [comment]
Ah I see what you mean - while xml should have one root element, there can be other stuff _around it_ other than the prolog, like comments and instructions: https://en.m.wikipedia.org/wiki/Root_element

That aside, the "easy" way is to write a hook to `str_replace` (or `substr`) it from the submission.  Or you can use the "mask" setting to fully customize the fields transformation, but you'll have to manually make all of xml for each field.  But you might actually just be able to put an "empty" prolog statement in the root, depending on what your endpoint wants to see.

**Comment by zaus** [comment]
To clarify the last part, if there is xml in the 'root' setting (with a `sprintf` placeholder for the content) it won't wrap the content.  So you could even set a comment instead:

     %s

**Comment by zaus** [comment]
Actually, ignore that last comment (can't edit on mobile?), I got confused between mask and xml handling.
