### ISSUE TITLE
Sending SOAP Requests

### ISSUE THREAD

**Issue by djvdm** [zaus/forms-3rdparty-xpost#21]
Hi,

We were wondering if you are available for hire to integrate SOAP requests using the forms-3rdparty-xpost plugin. I am working with a third party to have Gravity Forms send to a REPS back end but am not familiar with WP plugins and am not really following the instructions in the FAQ. If you are available to help with this, I will contact the company rep I am working with and we'll proceed from there. 

Thanks,

-Doug Van De Motter

**Comment by zaus** [comment]
Well, probably too late now but you can reach me through [my website](http://drzaus.com/contact) for these kind of requests...
