### ISSUE TITLE
help with xml mapping (for Zoho)

### ISSUE THREAD

**Issue by texasfalcon** [zaus/forms-3rdparty-xpost#22]
Can you tell me the best way to map the following, where Company, First Name, and Last Name are the 3rd party fields and the form submission fields are your-company, first-name, and last-name:

`<Leads>
<row no="1">
<FL val="Company">Your Company</FL>
<FL val="First Name">Hannah</FL>
<FL val="Last Name">Smith</FL>
</row>
</Leads>`

Thanks!

**Comment by zaus** [comment]
Sorry for the late reply, but according to [the Zoho API for insertRecords](https://www.zoho.com/crm/help/api/insertrecords.html) you'll need to write a hook to send the mapped response as an XML string (which I've explained in #5).

Other than that, I think you can map using the mask format, so you'd set up the root with a placeholder like

    <Leads><row no="1'>%s</row></Leads>

And then set up each mapping like

   your_company_field   -->   <FL val="Whatever">%s</FL>
