### ISSUE TITLE
Not getting debugging emails

### ISSUE THREAD

**Issue by macra** [zaus/forms-3rdparty-xpost#9]
I'm trying to get this plugin to work to post contact from 7 data to a lead method in workflow max. Still trying to get my head around how to map it all out. I have checked the debug mode from the 'Forms: 3rd Party Integration' plugin, but am not getting any emails at all. Any reason I'm not getting the debug emails?

**Comment by macra** [comment]
I'm wanting to use the post add method as described here;

http://www.workflowmax.com/api/lead-methods
I'm new to working with API's and it seems that it should be much easier than it's turning out to be.

**Comment by OllieJames** [comment]
Are you getting emails otherwise? i.e. contact form submission, new user emails, etc..

**Comment by zaus** [comment]
@macra - if as @OllieJames suggested and you're getting other emails, then check a couple more things:
1. Have you entered an email address in the Global values - email field?  You must have something there as well as enabling 'debug' mode
2. I've noticed that sometimes emails take a while to be sent/show up in my inbox -- it probably depends on your hosting provider configuration, but I've seen emails appear up to 20 minutes after submitting the form.
3. The debug emails may be filtered out as spam by your email provider.  Check any quarantines, etc.
4. If all else fails, you can try [turning on the Wordpress debug mode](http://codex.wordpress.org/Debugging_in_WordPress) (requires editing your `wpconfig.php` file) and checking out the debug log to see if there are any warnings or errors reported.

Also, what versions of the plugins are you using?  CF7 updated last year and made a breaking change, which the newer versions of my plugin account for, but I've seen people using out of date versions which aren't compatible.
